[compiler.solc]
exclude_paths = ["node_modules", "venv", ".venv", "lib", "script", "test"]
include_paths = ["node_modules"]
remappings = [
    "forge-std/=test/utils/forge-std/",
]

[compiler.solc.optimizer]
enabled = true
runs = 1000

[detectors]
exclude = ["unused-contract", "unused-import"]
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["node_modules", "lib", "script"]

[testing]
cmd = "revm"
