name: scan

on: [push]

jobs:
  tests:
    name: Wake scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run static analysis
        uses: Ackee-Blockchain/wake-detect-action@0.1.0
        with:
          export-sarif: true
        id: wake-detect

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.wake-detect.outputs.sarif }}
          checkout_path: ${{ github.workspace }}
